### ISSUE TITLE
Update UnRAR.exe and 7za.exe

### ISSUE THREAD

**Issue by 1aTa** [nzbgetcom/nzbget#102]
The builds included in the Windows version are from early 2019.

7za x86/x64: https://www.7-zip.org/a/7z2301-extra.7z

UnRAR x86: https://www.rarlab.com/rar/winrar-x32-700.exe
UnRAR x64: https://www.rarlab.com/rar/winrar-x64-700.exe

**Comment by magicdoublem** [comment]
Just in case you haven't come across this, you can always tell nzbget to use external binaries of these two. Go to settings / unpack...

In addition to your request, I'd bring up the idea to use just one of the two for all unpacking tasks, since they're pretty redundant nowadays.

**Comment by luckedea** [comment]
This is still on the radar, but didn't get into v23 release yet. Moving to v24.
