### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by mkanet** [nzbgetcom/nzbget#103]
Hi, I'm curious if there's a Windows that will be available soon.  I have been following the fork below
https://github.com/salami-ch/nzbget-win64/releases .  However, I'm not sure if I should just wait a little longer for your Windows binary release.

**Comment by luckedea** [comment]
After the `nzbget-ng` and `nzbgetcom` merge, this issue becomes obsolete.
We do provide all the necessary builds for all architectures.

winget support proposal is moved into a separate issue now https://github.com/nzbgetcom/nzbget/issues/138

Closing.
