### ISSUE TITLE
Build instructions do not work anymore

### ISSUE THREAD

**Issue by alex3305** [nzbgetcom/nzbget#106]
Hi 👋 ,

I was working on creating a Docker container based on the deprecated LinuxServer.io version, however building does not work anymore. At least not following the current instructions in the project [Readme](README.md):

https://github.com/nzbget-ng/nzbget/blob/a70a383c9db50cc5b5f122cc5a52ec4dc9c9abd7/README.md?plain=1#L112-L143

Can you please update the build instructions or provide me on how to build this? 

Thank you ❤️

**Comment by luckedea** [comment]
After combining `nzbget-ng` and `nzbgetcom` efforts - we are committed to support docker images ourselves. And of course we are modifying build instructions a lot too.

Please refer to Docker documentation https://github.com/nzbgetcom/nzbget/blob/develop/docker/README.md
Migration-related issue https://github.com/nzbgetcom/nzbget/issues/84#issuecomment-1884846500

Feel free to submit new issues, ask questions, please provide feedback too. I'm going to close this issue.
