### ISSUE TITLE
Is there a docker image repo for the new version?

### ISSUE THREAD

**Issue by famewolf** [nzbgetcom/nzbget#107]
I'm currently running nzbget on my Truenas.  I didn't see anything mentioned about docker?

**Comment by luckedea** [comment]
Please refer to https://github.com/nzbgetcom/nzbget/issues/106#issuecomment-1889057263 
I understand this is not fully the same question, but after the `nzbget-ng` and `nzbgetcom` migration we would be supporting the docker version ourselves. At the moment not all improvements from `nzbget-ng` exist here, but some are, some other problems were resolved too (differently).

I'm going to close this issue and keep https://github.com/nzbgetcom/nzbget/issues/84#issuecomment-1884846500 as main issue on the Docker subject.
