### ISSUE TITLE
Update update mechanism to point to new server

### ISSUE THREAD

**Issue by paul-chambers** [nzbgetcom/nzbget#110]
The code currently points to a server that is still under the control of the previous maintainer, and thus it's not possible to update nzbget using the internal update mechanism.

Change the update mechanism to point at nzbget-ng.github.io instead.

**Comment by luckedea** [comment]
Closing this as obsolete because of recent merge between `nzbget-ng` and `nzbgetcom`
We do provide and maintain auto-update system for `stable` and `testing` channels.
