### ISSUE TITLE
Please add version or Product name to exe properties on NZBGet!

### ISSUE THREAD

**Issue by ng4ever** [nzbgetcom/nzbget#114]
For some reason the original developer never wanted to and I have no idea why. :(

Someone else requested it too.

Main reason is to keep up to date with it on SUMo updater.

Here is my previous topic for it: https://github.com/nzbget/nzbget/issues/759

**Comment by luckedea** [comment]
Considering recent changes and merge of `nzbgetcom` and `nzbget-ng` we would definitely do that for v23.
As @salami-ch [mentioned ](https://github.com/nzbgetcom/nzbget/issues/114#issuecomment-1887028213)- the change is fairly trivial, but we'll use nzbget.com from now on. I'll keep it opened to be picked by @phnzb soon

**Comment by luckedea** [comment]
Didn't make it into v23, mostly due to amount of testing we had to do with new platforms support.
Updating milestone.
