### ISSUE TITLE
Add releases tab, update website download links

### ISSUE THREAD

**Issue by francislavoie** [nzbgetcom/nzbget#115]
I'm glad to see this get forked, and I hope this continues to be maintained! I love NZBGet, and I just found out the original repo was archived, which makes me sad.

I noticed that there's no Releases tab yet, and there's no builds with the changes since forking. I figured I'd open this issue to keep track of that. https://nzbget-ng.github.io/download will also need to be updated with those releases, which is sourced from the file here https://github.com/nzbget-ng/nzbget-ng.github.io/blob/trunk/_data/version.json

**Comment by dnzbk** [comment]
Closing as this is no longer relevant. The [release](https://github.com/nzbgetcom/nzbget/releases) tab is already available.
