### ISSUE TITLE
unrar and openssl version

### ISSUE THREAD

**Issue by woiza** [nzbgetcom/nzbget#116]
Hi,

any chance you could update unrar as well as openssl to a recent version which supports tls 1.3?

**Comment by luckedea** [comment]
At this moment
**OpenSSL** is:
:heavy_check_mark: fresh on Windows
:heavy_check_mark: fresh on macOS
:heavy_check_mark: fresh on Docker
:x: old on Linux (1.0.2d)

**unrar** is:
:heavy_check_mark: fresh on Docker 
:heavy_check_mark:fresh on macOS
:heavy_check_mark: fresh on Synology SPK
:x: old on SynoCommunity builds
:x: old on Linux

Keeping this issue open while we are updating it here and there..

**Comment by luckedea** [comment]
Closing this issue, versions of libraries has been reviewed and we advanced quite far from the original request by @woiza 
We still plan to detect the running environment (Status page in v24.2) and then bundle/suggest/fetch the best optimal tools for that environment.

My previous [comment ](https://github.com/nzbgetcom/nzbget/issues/116#issuecomment-1889130477) is also no longer valid, we bundle everything fresh at this point.
