### ISSUE TITLE
Windows Package Manager Community Repository / winget support

### ISSUE THREAD

**Issue by luckedea** [nzbgetcom/nzbget#138]
Based on https://github.com/nzbgetcom/nzbget/issues/103#issuecomment-1887017020 

We are committed to support as many platforms as possible, so this is a good suggestion.
Scope:
- review what it takes to support winget
- review compatibility with nzbget internal auto-update system

**Comment by zotabee** [comment]
Getting a hash error with a Winget upgrade between 23.0 and 24.0

Found NZBGet [nzbget.nzbget] Version 24.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/nzbgetcom/nzbget/releases/download/v24.0/nzbget-24.0-bin-windows-setup.exe
  ██████████████████████████████  12.2 MB / 12.2 MB
Installer hash does not match.

**Comment by zotabee** [comment]
https://github.com/microsoft/winget-pkgs/blob/master/manifests/n/nzbget/nzbget/24.0/nzbget.nzbget.installer.yaml

  InstallerSha256: E152747BCAA057C9A3736BE648FB6DBD7C0E06C11C45BB1EFFD87C3A79C2D922

While downloading the installer gives me (SHA-256) : D213945D9C5CFFECBA26D8F672204940F8574FC948D4013F87C1D0AC7534329E

**Comment by luckedea** [comment]
winget is currently fully supported, v24 winget version has been updated.
Future releases would be automatically published during deployment to prevent any conflicts.

Thank you.
Closing the issue.
