### ISSUE TITLE
Ubuntu Build: "configure: error: Could not find Boost.JSON library" 

### ISSUE THREAD

**Issue by sanderjo** [nzbgetcom/nzbget#162]
`./configure` errors out with

```
checking for main in -lboost_json... no
configure: error: Could not find Boost.JSON library
```

I thought that `sudo apt-get install libboost-all-dev` would solve it, but not so.

Tips welcome

Maybe related to https://github.com/nzbgetcom/nzbget/issues/88

On Ubuntu on RISC-V

```
sander@nezha:~/git/nzbget.com$ sagi libboost-dev
[sudo] password for sander: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libboost-dev is already the newest version (1.74.0.3ubuntu7).
libboost-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
sander@nezha:~/git/nzbget.com$ sagi libboost-all-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libboost-all-dev is already the newest version (1.74.0.3ubuntu7).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
sander@nezha:~/git/nzbget.com$ 
```

**Comment by sanderjo** [comment]
I tried with a Ubuntu docker on Ubuntu x86, and same problem. So not related to the RISC-V setup

`apt-get install build-essential libncurses5-dev libssl-dev libxml2-dev zlib1g-dev pkg-config git autoconf -y
`

```
checking for library containing hstrerror... none required
checking for main in -lboost_json... no
configure: error: Could not find Boost.JSON library
```

**Comment by Prinz23** [comment]
The issue that i have too is probably that the JSON part was only added in boost lib 1.75.0:

> Version 1.75.0
December 11th, 2020 19:50 GMT
New Libraries: JSON

So this new requirement is simply not compatible with older OS versions, that still have sometimes way older versions.

**Comment by dnzbk** [comment]
Indeed, the latest version of the libboost-all-dev package available on my Debian 12 system is 1.74.
In fact, you don't really need to install this package which includes all the Boost libraries. Most of the Boost libraries can be installed separately and in newer versions, such as Boost.Json.
Try searching for the libboost-json package and install its dev version.
For example, on my system, I install Boost.Json like this: apt install libboost-json1.81-dev

**Comment by sanderjo** [comment]
> For example, on my system, I install Boost.Json like this: apt install libboost-json1.81-dev

Which system is that? As it does not exist on my Ubuntu:

```
root@zwart2204:~# apt install libboost-json1.81-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libboost-json1.81-dev
E: Couldn't find any package by glob 'libboost-json1.81-dev'
root@zwart2204:~# 

root@zwart2204:~# apt search libboost-json
Sorting... Done
Full Text Search... Done
root@zwart2204:~# 

```

**Comment by Prinz23** [comment]
I could also not find any newer version for my OS (a forked Debian 10 for a single board). 

My solution that worked was download the latest source tar ball 1.84.0 and compile and install it. After this the configure and compiling of nzbget works fine again.

**Comment by phnzb** [comment]
@sanderjo NZBGet v23+ requires [Boost.JSON library](https://github.com/nzbgetcom/nzbget/blob/develop/INSTALLATION.md#3-prerequisites-on-posix) to build, available in Boost since 1.75.0.
Old Debian / Ubuntu LTS does not have required version.
Your options is:
- use custom repository / PPA with prebuilt packages (for me on Ubuntu 22.04 works well https://launchpad.net/~mhier/+archive/ubuntu/libboost-latest)
```
sudo add-apt-repository ppa:mhier/libboost-latest
sudo apt update
sudo apt install libboost-json1.83-dev libboost-json1.83.0
```
- build Boost.JSON from sources

P.S. we provide linux installer, working out-of-box with most linux distribution, you can try it
current testing: https://github.com/nzbgetcom/nzbget/releases/download/testing/nzbget-latest-testing-bin-linux.run
v23 pre-release: https://github.com/nzbgetcom/nzbget/releases/download/v23.0/nzbget-23.0-bin-linux.run

**Comment by sanderjo** [comment]
@phnzb Thanks. However, this is all on my riscv64 system, verifying that https://github.com/nzbgetcom/nzbget/pull/18 now works.

Building boost.json ... I tried that on x86 ... without succes (too difficult for me).

I doubt the PPA is available for riscv64. And pre-built nzbget for riscv64, I doubt that too.  I will try, and then report back. If it doesn't ... so be it.

**Comment by sanderjo** [comment]
Update: as expexted: ppa does not work on riscv64:

```
sudo add-apt-repository ppa:mhier/libboost-latest
sudo apt update

sander@nezha:~$ sudo apt install libboost-json1.83-dev libboost-json1.83.0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libboost-json1.83-dev
E: Couldn't find any package by glob 'libboost-json1.83-dev'
E: Unable to locate package libboost-json1.83.0
E: Couldn't find any package by glob 'libboost-json1.83.0'

```

**Comment by phnzb** [comment]
@sanderjo we have decided to include support to riscv64 platform to universal nzbget linux installer. Could you test the build from [this run](https://github.com/nzbgetcom/nzbget/actions/runs/7899312304) on your system (already tested on riscv64 QEMU VM) ?

**Comment by sanderjo** [comment]
Cool. I'll do that tomorrow morning ... when I've access to my RISCV64 SBC.

**Comment by sanderjo** [comment]
And FWIW: the BOOST stuff seems to be inside the nzbget binary. Looks good.

```
sander@nezha:~/nzbget$ strings nzbget | grep -i boost
N5boost6system14error_categoryE
N5boost6system6detail22generic_error_categoryE
N5boost6system6detail21system_error_categoryE
N5boost6system6detail22interop_error_categoryE
/build/toolchain/riscv64/output/host/riscv64-buildroot-linux-musl/sysroot/usr/include/boost/json/value.hpp
boost.json
./boost/json/impl/static_resource.ipp
./boost/json/impl/array.ipp
./boost/json/impl/object.ipp
./boost/json/impl/string.ipp
./boost/json/impl/pointer.ipp
./boost/json/detail/impl/string_impl.ipp
./boost/json/value.hpp
key_value_pair<std::nullptr_t, boost::json::storage_ptr&>
key_value_pair<boost::json::value, boost::json::storage_ptr&>
./boost/json/impl/parser.ipp
./boost/json/impl/parse.ipp
./boost/json/impl/stream_parser.ipp
./boost/json/basic_parser_impl.hpp
*ZN5boost4json15make_error_codeENS0_5errorEE5codes
*ZN5boost4json20make_error_conditionENS0_9conditionEE5codes
./boost/json/impl/null_resource.ipp
key_value_pair<boost::json::value>
N5boost9exceptionE
N5boost16exception_detail10clone_baseE
N5boost9container3pmr15memory_resourceE
N5boost4json6detail15shared_resourceE
N5boost4json6detail16default_resourceE
N5boost6system6detail12std_categoryE
N5boost6system12system_errorE
N5boost4json18monotonic_resourceE
N5boost4json15static_resourceE
N5boost4json6detail13null_resourceE
N5boost10wrapexceptISt9bad_allocEE
N5boost10wrapexceptISt12length_errorEE
N5boost10wrapexceptISt16invalid_argumentEE
N5boost10wrapexceptISt12out_of_rangeEE
N5boost10wrapexceptINS_6system12system_errorEEE

```

**Comment by phnzb** [comment]
@sanderjo Both testing and current stable (v23) builds updated with riscv64 support.

**Comment by phnzb** [comment]
closing as completed
