### ISSUE TITLE
Dietpi - software support. Seems as action is needed

### ISSUE THREAD

**Issue by tundrablasen** [nzbgetcom/nzbget#163]
https://dietpi.com/forum/t/nzbget-new-maintainer-dietpi-software-already-updated/18425/2

seems to be that nzbget.com team would need to make some adjustments so that dietpi can support the follow up project

**Comment by phnzb** [comment]
@tundrablasen 
The thread you linked is outdated, we already have fulfilled all requirements - see #57, #58

@MichaIng Can you please confirm? We are happy to assist if needed.

**Comment by tundrablasen** [comment]
Ok I missed that. Thanks 🙏

**Comment by MichaIng** [comment]
Jep, we migrated to this fork with DietPi v8.25, released mid December 🙂.

**Comment by tundrablasen** [comment]
> Jep, we migrated to this fork with DietPi v8.25, released mid December 🙂.

I’m obviously a potato. Sorry and thanks for the work
