### ISSUE TITLE
Extension manager failed to download - 7zip not found

### ISSUE THREAD

**Issue by sdburrows** [nzbgetcom/nzbget#164]
On v23, when trying to add new script via Extension Manager, I received the following error message:

```
Failed to download ExtendedUnrar
Failed to unpack X:\NZBGet\Temp\extension-ExtendedUnrar.tmp.zip

Request: downloadextension?=https%3A%2F%2Fgithub.com%2Fnzbgetcom%2FExtension-ExtendedUnrar%2Freleases%2Fdownload%2Fv2.0%2Fextendedunrar-2.0-dist.zip&=ExtendedUnrar
```

**Comment by dnzbk** [comment]
Apparently 7zip was not found. 
Could you check that SevenZipCmd (SETTINGS->UNPACK) is correct?

And yes, this type of error message should definitely be improved.

**Comment by sdburrows** [comment]
@dnzbk 

Thanks, fixed it by changing the entry to `${AppDir}\7za.exe`
