### ISSUE TITLE
Wrong permissions after unrar on some NZBs

### ISSUE THREAD

**Issue by Anuskuss** [nzbgetcom/nzbget#165]
I use `unrar -ai` and everything worked correctly until I found this one particular NZB:
1. Downloading with DirectUnpack
```shell
$ stat -c '%A %u %n' * _unpack/* | grep -v 'r0[1-9]\|r[1-6][0-9]'
-rw-r--r-- 1000 149539-0.mkv
-rw-r--r-- 1000 149539-1.jpg
-rw-r--r-- 1000 149539-2.nfo
-rw-r--r-- 1000 149539-2.r00
-rw-r--r-- 1000 149539-2.rar
drwxr-xr-x 1000 _unpack
-rw-r--r-- 1000 _unpack/censored.mkv
```

2. Download (and unrar) finished, PAR2 files come in
```shell
$ stat -c '%A %u %n' * _unpack/* | grep -v 'r0[1-9]\|r[1-6][0-9]'
-rw-r--r-- 1000 149539-0.mkv
-rw-r--r-- 1000 149539-0.par2
-rw-r--r-- 1000 149539-1.jpg
-rw-r--r-- 1000 149539-1.par2
-rw-r--r-- 1000 149539-2.nfo
-rw-r--r-- 1000 149539-2.par2
-rw-r--r-- 1000 149539-2.r00
-rw-r--r-- 1000 149539-2.rar
-rw-r--r-- 1000 149539-2.sfv
drwxr-xr-x 1000 _unpack
-rw-r--r-- 1000 _unpack/censored.mkv
```

3. Files get their canonical name, unpacking restarts
`[INFO] Found archive files not processed by direct unpack, unpacking all files again`
```shell
$ stat -c "%A %u %n" * _unpack/* | grep -v 'r0[1-9]\|r[1-6][0-9]'
-rw-r--r-- 1000 149539-0.par2
-rw-r--r-- 1000 149539-1.par2
-rw-r--r-- 1000 149539-2.par2
-rw-r--r-- 1000 censored.nfo
-rw-r--r-- 1000 censored-proof.jpg
-rw-r--r-- 1000 censored.r00
-rw-r--r-- 1000 censored.rar
-rw-r--r-- 1000 censored-sample.mkv
-rw-r--r-- 1000 censored.sfv
drwxr-xr-x 1000 _unpack
-rwx------ 1000 _unpack/censored.mkv
```

4. Unpacking finished
```shell
$ stat -c "%A %u %n" * | grep -v 'r0[1-9]\|r[1-6][0-9]'
-rwx------ 1000 censored.mkv
-rw-r--r-- 1000 censored.nfo
-rw-r--r-- 1000 censored-proof.jpg
-rw-r--r-- 1000 censored-sample.mkv
-rw-r--r-- 1000 censored.sfv
```

Notice how in step 3 the file permissions get changed from the normal 644 (`rw-r--r--`) to 700 (`rwx------`) which leads to problems further down the line. I tried to combat this behaviour with ACLs but that only works for newly created files so it looks like it's being set deliberately. Those permissions do not come from the RAR file (`-ai` should ignore them anyway).

The file in question can be found on DS (`4156a6cc26932bfe4faf54beb77875f7e8841e22`). I can share the NZB if you don't have access to DS.

**Comment by Anuskuss** [comment]
> I use `unrar -ai` and everything worked correctly until I found this one particular NZB:

**Comment by parnic** [comment]
> > I use `unrar -ai` and everything worked correctly until I found this one particular NZB:

My bad.

**Comment by Anuskuss** [comment]
Not that it really matters but this whole thing could've been avoided by just using `DirectRename` (it's faster, too!).
