### ISSUE TITLE
cmake build (develop branch) on Linux incomplete

### ISSUE THREAD

**Issue by bacon-cheeseburger** [nzbgetcom/nzbget#167]
I was under the impression that the cmake transition was complete except for embedded systems but this doesn't seem to be the case:

$ export CFLAGS+="-march=x86-64"
$ export CXXFLAGS+="-march=x86-64"
$ cmake -S . -B build -DENABLE_TESTS=OFF
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.a (found version "3.1.5")
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.a (found version "1.3")
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.14")
-- Found Boost: /lib/x86_64-linux-gnu/cmake/Boost-1.81.0/BoostConfig.cmake (found version "1.81.0") found components: json
-- Configuring done (0.8s)
-- Generating done (0.0s)
-- Build files have been written to: /test/nzbget-r2395.git+c116a639/build
$ cmake --build build -j12
[ 10%] Building CXX object lib/CMakeFiles/Par2.dir/par2/criticalpacket.cpp.o
[ 10%] Building CXX object lib/CMakeFiles/Yencode.dir/yencode/SimdInit.cpp.o
[ 16%] Building CXX object lib/CMakeFiles/Par2.dir/par2/commandline.cpp.o
[ 16%] Building CXX object lib/CMakeFiles/Par2.dir/par2/crc.cpp.o
[ 16%] Building CXX object lib/CMakeFiles/Yencode.dir/yencode/Ssse3Decoder.cpp.o
[ 20%] Building CXX object lib/CMakeFiles/Par2.dir/par2/datablock.cpp.o
[ 30%] Building CXX object lib/CMakeFiles/Yencode.dir/yencode/ScalarDecoder.cpp.o
[ 30%] Building CXX object lib/CMakeFiles/Yencode.dir/yencode/Sse2Decoder.cpp.o
[ 30%] Building CXX object lib/CMakeFiles/Par2.dir/par2/creatorpacket.cpp.o
[ 33%] Building CXX object lib/CMakeFiles/Par2.dir/par2/descriptionpacket.cpp.o
[ 36%] Building CXX object lib/CMakeFiles/Yencode.dir/yencode/PclmulCrc.cpp.o
[ 40%] Building CXX object lib/CMakeFiles/Yencode.dir/yencode/SimdDecoder.cpp.o
[ 43%] Building CXX object lib/CMakeFiles/Yencode.dir/yencode/NeonDecoder.cpp.o
[ 46%] Building CXX object lib/CMakeFiles/Yencode.dir/yencode/AcleCrc.cpp.o
[ 50%] Building CXX object lib/CMakeFiles/Yencode.dir/yencode/SliceCrc.cpp.o
[ 53%] Building CXX object lib/CMakeFiles/Par2.dir/par2/diskfile.cpp.o
[ 56%] Building CXX object lib/CMakeFiles/Par2.dir/par2/filechecksummer.cpp.o
[ 60%] Building CXX object lib/CMakeFiles/Par2.dir/par2/galois.cpp.o
[ 63%] Building CXX object lib/CMakeFiles/Par2.dir/par2/mainpacket.cpp.o
[ 66%] Building CXX object lib/CMakeFiles/Par2.dir/par2/md5.cpp.o
[ 70%] Building CXX object lib/CMakeFiles/Par2.dir/par2/par2fileformat.cpp.o
[ 73%] Building CXX object lib/CMakeFiles/Par2.dir/par2/par2repairer.cpp.o
[ 76%] Building CXX object lib/CMakeFiles/Par2.dir/par2/par2repairersourcefile.cpp.o
[ 80%] Building CXX object lib/CMakeFiles/Par2.dir/par2/parheaders.cpp.o
[ 83%] Building CXX object lib/CMakeFiles/Par2.dir/par2/recoverypacket.cpp.o
[ 86%] Building CXX object lib/CMakeFiles/Par2.dir/par2/reedsolomon.cpp.o
[ 90%] Linking CXX static library libYencode.a
[ 90%] Built target Yencode
[ 93%] Building CXX object lib/CMakeFiles/Par2.dir/par2/verificationhashtable.cpp.o
[ 96%] Building CXX object lib/CMakeFiles/Par2.dir/par2/verificationpacket.cpp.o
[100%] Linking CXX static library libPar2.a
[100%] Built target Par2

Any idea when this is going to be fixed?

**Comment by dnzbk** [comment]
This work is close to completion, but we still have to some a few related issues before full switchover.
With v23 released, I'll work on it soon.
For now please use autotools.
