### ISSUE TITLE
macOS: "Could not establish connection to downloader (background process)"

### ISSUE THREAD

**Issue by cryo-kronos** [nzbgetcom/nzbget#184]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### NZBGet Version

v23-stable

### Platform

macOS

### Environment

```markdown
2012 Mac Mini
macOS Mojave 10.14.6
Intel 64-bit
Python 3.11
Running in Docker: No
```

### Current Behavior

nzbget is not working for me on macOS Mojave. nzbget appears to be running as it shows up in Activity Monitor, but when you try to connect to the web interface, it says "Could not establish connection to downloader (background process)." 

The crash log shows the following:

    Process: nzbget [88372] Path: /Applications/NZBGet.app/Contents/Resources/daemon/usr/local/bin/nzbget Identifier: nzbget Version: ??? Code Type: X86-64 (Native) Parent Process: NZBGet [88350] Responsible: nzbget [88372] User ID: 501

    Date/Time: 2024-02-22 12:48:30.858 -0800 OS Version: Mac OS X 10.14.6 (18G9323) Report Version: 12 Anonymous UUID: E737FFE7-1234-6B4E-716F-45D82B8FB5A5

    Time Awake Since Boot: 87000 seconds

    System Integrity Protection: disabled

    Crashed Thread: Unknown

    Exception Type: EXC_CRASH (SIGABRT) Exception Codes: 0x0000000000000000, 0x0000000000000000 Exception Note: EXC_CORPSE_NOTIFY

    Termination Reason: DYLD, [0x9] <unknown>

    Dyld Error Message: cannot load 'nzbget' (load command 0x80000034 is unknown)

    Binary images description not available

### Expected Behavior

To run properly, of course, like the old version of nzbget.

**Comment by phnzb** [comment]
@cryo-kronos problem confirmed, current bulds support macOS Monterey (12.0+) versions only. Fixes in progress.

**Comment by cobbb** [comment]
@phnzb & @cryo-kronos - I'm having the same issue, identical hardware but running 10.15.7. 
Just an FYI, as I see a fix is already in progress.  That being said if you'd like any additional logs / reports please LMK. 
thanks

**Comment by cryo-kronos** [comment]
This problem has returned with the 24.1 release.

**Comment by phnzb** [comment]
@cryo-kronos Just checked - macOS Mojave 10.14.6 - x64 build working as expected. Are you using [x64 build](https://github.com/nzbgetcom/nzbget/releases/download/v24.1/nzbget-24.1-bin-macos-x64.zip) ? Universal binary requries macOS Monterey 12+.

**Comment by cryo-kronos** [comment]
> @cryo-kronos Just checked - macOS Mojave 10.14.6 - x64 build is working as expected. Are you using [x64 build](https://github.com/nzbgetcom/nzbget/releases/download/v24.1/nzbget-24.1-bin-macos-x64.zip) ? Universal binary requries macOS Monterey 12+.

The x64 build works. It was the universal binary I downloaded from the main page (https://nzbget.com/download/) that didn't work. My understanding is that universal binaries work with both Intel and Apple Silicon. On the download page it even says "macOS 10.13 High Sierra and later, Intel / Apple Silicon." I downloaded it on the Mojave system and it gave me the universal binary automatically.

But in the future, I download the x64 version GitHub for Mojave running on my Mac Mini. 

Maybe you could edit the download page to mention that Monterey is the minimum version for the universal binary.

Thanks.
