### ISSUE TITLE
Script Support: Send download to SickChill (along the lines of nzbToMedia)

### ISSUE THREAD

**Issue by rEes9P** [nzbgetcom/nzbget#190]
### Is there already an issue for this request?

- [X] I have checked older issues, open and closed

### Platform

All

### Describe the enhancement you'd like

While clinton-hall's nzbToMedia scripts have been extremely useful and rock solid for years, it would be nice to have an official script that does the simple task of sending a download to SickChill for processing. It could forego the transcode options that the nzbToMedia scripts include and just do the singular job of passing the processing over to SickChill.

**Comment by MattPark** [comment]
@miigotu @bksteve

**Comment by dnzbk** [comment]
A new [NotifySickChill](https://github.com/nzbgetcom/Extension-NotifySickChill) extension is available and can be installed via Extension Manager. 
Feel free to test it, thanks.

**Comment by rEes9P** [comment]
Brilliant! Just gave it a spin and it works beautifully. Thanks :-)
