### ISSUE TITLE
VIDEOSORT extension on NZBGet v23

### ISSUE THREAD

**Issue by ng4ever** [nzbgetcom/nzbget#201]
### Is there already an issue for this request?

- [X] I have checked older issues, open and closed

### Describe your issue

Files do not unpack pretty without _ and out of folders anymore :(

**Comment by dnzbk** [comment]
Thank you for the report, can you please provide more information about the used data (nzb file for example), OS and Python?
I'm testing and I can't easily replicate the problem.

**Comment by ng4ever** [comment]
Windows 11, python-2.7.17.amd64

This is the VIDEOSORT I am using: https://github.com/nzbget/VideoSort

**Comment by dnzbk** [comment]
Tested VideoSort 8.0 and python 2.7 with NZBGet v23.0 - it works for me.
Can you try to resave `(SETTINGS->Save All Changes)` your VideoSort settings after NZBGet update and test it again?
Also consider upgrading VideoSort to a newer and supported version: [VideoSort 10.1](https://github.com/nzbgetcom/Extension-VideoSort).
It can be easily installed by the Extension Manager.
But note that the new version requires at least Python 3.8.0 to be installed.

**Comment by ng4ever** [comment]
> Tested VideoSort 8.0 and python 2.7 with NZBGet v23.0 - it works for me. Can you try to resave `(SETTINGS->Save All Changes)` your VideoSort settings after NZBGet update and test it again? Also consider upgrading VideoSort to a newer and supported version: [VideoSort 10.1](https://github.com/nzbgetcom/Extension-VideoSort). It can be easily installed by the Extension Manager. But note that the new version requires at least Python 3.8.0 to be installed.

Thanks tried that didn't work. 

Trying VideoSort 10.1 but when I download it then extract it the .py file is Main. I still tried adding it but no VideoSort appears in NZBGet now. :(

![image](https://github.com/nzbgetcom/nzbget/assets/17295139/6e60f87e-5467-4b7a-9f9f-1f155ad3fe2e)

I have Python 3.8.0 or greater installed

**Comment by ng4ever** [comment]
Ok I figured out you can install extensions, like you said, from within NZBGet but I always get this error when I try :(


Failed to download VideoSort

Failed to unpack C:\ProgramData\NZBGet\tmp\extension-VideoSort.tmp.zip

Request: downloadextension?=https%3A%2F%2Fgithub.com%2Fnzbgetcom%2FExtension-VideoSort%2Freleases%2Fdownload%2Fv10.0%2Fvideosort-10.0-dist.zip&=VideoSort



I do run NZBGet on a limited or standard windows account not admin.

**Comment by dnzbk** [comment]
If you are installing the extension manually (from github), make sure you install it in the correct directory.
The default path to the correct directory is `C:\ProgramData\NZBGet\scripts\`.
In case of VideoSort, it should be `C:\ProgramData\NZBGet\scripts\VideoSort`.
Also double-check if path to ScriptDir is correct: `SETTINGS->PATHS->ScriptDir`

As for the error `Failed to unpack C:\ProgramData\NZBGet\tmp\extension-VideoSort.tmp.zip`,
the problem may be in the wrong path to `7za.exe`, which is required by Extension Manager to unpack the extensions.
Make sure that the path to `7za.exe` in `SETTINGS->UNPACK->SevenZipCmd` is correct.
Usually `7za.exe` is located in `C:\Program Files\NZBGet\`, as it comes with the main application.

**Comment by ng4ever** [comment]
Thanks finally got videosort to install but now whenever I download something it deletes the file after the whole process :(

Maybe something is wrong here? 

![image](https://github.com/nzbgetcom/nzbget/assets/17295139/54dcaf14-8841-4b74-8a50-ebcdbd8c6297)


or here

![image](https://github.com/nzbgetcom/nzbget/assets/17295139/1e2c348c-7fba-40be-a782-8bd0a4af8188)

**Comment by ng4ever** [comment]
Thanks all fixed! 

Greatly appreciated!
