### ISSUE TITLE
VideoSort Formatting Error

### ISSUE THREAD

**Issue by sdburrows** [nzbgetcom/nzbget#206]
### Is there already an issue for this request?

- [X] I have checked older issues, open and closed

### Describe your issue

NZBGET version 23.1-testing-20240313
VideoSort version 10.1

VideoSort format %qf for "WEB-DL" is listed as 'WEB" rather than "WEB-DL". The original version name the files properly. 

%qf - video format (HTDV, BluRay, WEB-DL);

**Comment by dnzbk** [comment]
For pattern matching VideoSort uses the [guessit](https://guessit-io.github.io/guessit/) library and referring to its [documentation](https://guessit-io.github.io/guessit/migration2to3/#source-former-format-property) starting with version 3 guessit formats sources of type `WEBDL` or `WEB-DL` into `Web`.
I'm not sure it's worth fixing but the VideoSort documentation needs to be updated for sure.
