### ISSUE TITLE
How to disable not being able to download a duplicate nzb file ? 

### ISSUE THREAD

**Issue by ng4ever** [nzbgetcom/nzbget#212]
### Is there already an issue for this request?

- [X] I have checked older issues, open and closed

### Describe your issue

It always seems to delete/skip it right now.

I bet it is really simple to fix. Must be blind :(

**Comment by dnzbk** [comment]
Duplicate check can be disabled at `SETTINGS`->`INCOMING NZBS`->`DupeCheck`.
