### ISSUE TITLE
PAR2 verification failes on big files

### ISSUE THREAD

**Issue by Anuskuss** [nzbgetcom/nzbget#244]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### NZBGet Version

v24-stable

### Platform

Linux/Docker

### Environment

```markdown
Linux 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux
```

### Current Behavior

Par failes without even trying

### Expected Behavior

At least check the checksums

### Logs

```
DETAIL	Par: Loaded 4 new packets
DETAIL	Par: There are 1 recoverable files and 0 other files.
DETAIL	Par: The block size used was 5242880 bytes.
DETAIL	Par: There are a total of 7402 data blocks.
DETAIL	Par: The total size of the data files is 38805035467 bytes.
DETAIL	Par: Verifying source files:
ERROR	Par: File size for file.ext is too large.
WARNING	File file.ext with 7402 block(s) is missing
```

### Extra information

Is this a 32-bit issue? Works fine via command line:
```shell
$ par2verify 6ea4673e9dd7670c94a215ebac659056.par2 
Loading "6ea4673e9dd7670c94a215ebac659056.par2".
Loaded 4 new packets
Loading "6ea4673e9dd7670c94a215ebac659056.par2".
No new packets found

There are 1 recoverable files and 0 other files.
The block size used was 5242880 bytes.
There are a total of 7402 data blocks.
The total size of the data files is 38805035467 bytes.

Verifying source files:

Opening: "censored.mkv"
Target: "censored.mkv" - found.

All files are correct, repair is not required.
```

**Comment by Anuskuss** [comment]
Reverted back and saw that it used to work in v21:
```
DETAIL	Par: Loaded 4 new packets
DETAIL	Par: There are 1 recoverable files and 0 other files.
DETAIL	Par: The block size used was 5242880 bytes.
DETAIL	Par: There are a total of 7402 data blocks.
DETAIL	Par: The total size of the data files is 38805035467 bytes.
DETAIL	Par: Verifying source files:
INFO	Verifying file censored.mkv
DETAIL	Quickly verified good file censored.mkv
DETAIL	Par: All files are correct, repair is not required.
```

It finished very quickly so there's was certainly no checksum calculated. Don't know if that's intentional though.

**Comment by luckedea** [comment]
Linked issue to address first https://github.com/nzbgetcom/nzbget/issues/93

**Comment by chtk** [comment]
I think this might a cmake vs. autoconf issue. 

Builds using autoconf property detect HAVE_FSEEKO and writes `define HAVE_FSEEKO` to config.h. CMake keeps it undefined. 

The define HAVE_FSEEKO is used in `lib/par2/diskfile.cpp` to conditionally set `MaxOffset`. 

`MaxOffset` is used to conditionally raise an error in `DiskFile::Open`
