### ISSUE TITLE
New icons not working via reverse proxy

### ISSUE THREAD

**Issue by rg9400** [nzbgetcom/nzbget#245]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### NZBGet Version

v23-stable

### Platform

All

### Environment

```markdown
Version: 24.1-testing-20240425
Docker: Yes
OS: Ubuntu 22.04
Reverse Proxy: NGINX
```

### Current Behavior

With the below NGINX configuration, NZBGet is loading fonts at https://domain.com/lib/material-icons.woff2. This location does not exist because NZBGet is running at https://domain.com/nzbget, and so the icons fail to render. Even though there is no explicit setting to add a subfolder on NZBGet, everything else runs perfectly except for these new icons. It works fine outside of the reverse proxy.

```nginx
location ^~ /nzbget {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app nzbget;
    set $upstream_port 6789;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
}
```

### Expected Behavior

The icons should be available on https://domain.com/nzbget/lib/material-icons.woff2 as well, so that they can render like the old icons used to.

### Steps To Reproduce

1. Use the above NGINX config with SWAG or set up any reverse proxy for NZBGet, then access it via the RP to verify if the new icons are rendering or not.

### Logs

N/A

### Extra information

N/A

**Comment by dnzbk** [comment]
This [commit](https://github.com/nzbgetcom/nzbget/commit/2a39a524788efe8bb6f0c6460fed6fdbffcbed0c) should have fixed this issue. Please upgrade to the latest test version to make sure, thanks.

**Comment by rg9400** [comment]
This is fixed now
