### ISSUE TITLE
Unable to unpack rar files after upgraded nzbget docker to v24

### ISSUE THREAD

**Issue by baruser123** [nzbgetcom/nzbget#255]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### NZBGet Version

v23-stable

### Platform

Linux/Docker

### Environment

```markdown
I'm not be able to select nzbget v24 as Nzbget Version so i select V23 for now

Environment
Synology 1813+
DSM 7.1.1-42962 Update 6
Running in Docker: Yes
```

### Current Behavior

I'm not be able to select nzbget v24 as Nzbget Version so i select V23 for now

After upgrading today to nzbget docker version v24, nzbget is unable to extract rar files. After downloading and verify all the files the download goes directly to history with the status failed. The error on the log of the download is Unpack for .... failed.

### Expected Behavior

Unpack this download

### Steps To Reproduce

On my Synology 1813+ with docker upgrade to nzbget docker via nzbgetcom/nzbget:latest to v24. Afterwards start a random download with rar files to unpack. And the issue appear
After i'm going back to version v23 with nzbgetcom/nzbget:v23.0 the problem is gone
Going back to v24 and the issue appear again. 
All tried with the same download

### Logs

In the history log:
Unpack for .... failed
In the message log
Unpack for .... failed

### Extra information

I think the problem is caused because of the use of unrar version 7 with v24. It looks like that my synology doesn't support unrar 7x. I had the same problem when sabnzbd started with the use of unrar v7. Linuxserver gave us a workaround to install back unrar v6 after a docker update. They did this to add a environment variable       - DOCKER_MODS=lscr.io/linuxserver/mods:universal-unrar6

See also:
https://github.com/linuxserver/docker-mods/tree/universal-unrar6
https://github.com/linuxserver/docker-sabnzbd/issues/219
https://github.com/sabnzbd/sabnzbd/issues/2823

So it would be great if something like that is also possible with the nzbget docker v24. Or maybe add also unrar6 in ${AppDir}/unrar so we can change ${AppDir}/unrar to ${AppDir}/unrar6 in settings.

Or something like a downloadable unrar.zip, so we can put this in our config dir and redirect unrar in settings to this

For now i revert to v23 to be able to use nzbget

**Comment by phnzb** [comment]
@baruser123 Synology 1813+ has Intel Atom CPU, that's not compatible with x86-64-v2. In the future, we may add a separate unrar6 binary to the Docker container for such cases, the user will be able to change the UnrarCmd in the settings.

**Comment by baruser123** [comment]
> @baruser123 Synology 1813+ has Intel Atom CPU, that's not compatible with x86-64-v2. In the future, we may add a separate unrar6 binary to the Docker container for such cases, the user will be able to change the UnrarCmd in the settings.

Thanks for your quick reply. I will stay on v23 for now then. And hopefully there will be an seperate unrar6 in the future.

**Comment by phnzb** [comment]
@baruser123 We decided to make unrar6 default in docker container and include optimized unrar7 binary as well. If you want, you can switch to a `testing` docker container.

**Comment by baruser123** [comment]
> @baruser123 We decided to make unrar6 default in docker container and include optimized unrar7 binary as well. If you want, you can switch to a `testing` docker container.

Thank you very very much for this quick fix. Change the docker to testing and updated the docker to version 24.1. Can confirm that unpacking is possible again. Thanks again!!!

one quick question. i saw in the release notes that the version is change to "increase version to v24.1", is it possible in the future to use the complete release version. like now 24.1-testing-20240503. because if you go to check update nzbget says there is still a new testing release. i know it's just cosmetic :)

![image](https://github.com/nzbgetcom/nzbget/assets/1168526/d9a9d6cf-50d4-4639-b828-b832e6c005bf)
