### ISSUE TITLE
Disabling a news server result in 100% CPU usage, as reported by top, in 24.1-stable and 24.2-testing

### ISSUE THREAD

**Issue by ssl-3** [nzbgetcom/nzbget#300]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### NZBGet Version

v24.1-stable

### Platform

Linux/Docker

### Environment

```markdown
Void Linux (was reasonably up to date, is now up to the minute)
Docker
x64
```

### Current Behavior

Disabling a news server (in the GUI, in nzbget.conf, in nuking and restoring settings, in very selectively merging backed up configs to current config) always results in 100% CPU usage reported in top by nzbget, at least in docker (have not checked other arrangements).

It does not seem to matter what position this server is in, whether Server1 or Server2.

It does not seem to matter whether nzbget is actually reportedly doing anything or not.

### Expected Behavior

Disabling server should simply take it out of the loop, and should not ever result in what appears to be silly-high CPU usage

### Steps To Reproduce

1.  Install nzbget with docker (linuxserver.io, nzbgetcom, testing, stable, whatever) with a clean never-touched default config.
2.  Disable the default server by any method (gui, text editor)
3.  [Re]load nzbget
4.  run top, observe 100% CPU usage by nzbget process and a resultant load average of at least 1.

Or:

1.  Open [working, configured] nzbget settings in GUI
2.  Disable any news server.
3. [...]  same results.

and then:

1.  Re-enable that same server.
2.  Things get quiet.  Reported CPU usage becomes much more sensible (~0% if nothing is downloading)

### Logs

Nothing meaningful was found logged, or on the console.  Nothing important seemed to show up in strace but I'm certainly no expert there.  A whole lot of nothing was visibly produced for diagnostic data.  :)

### Extra information

I appreciate everything you folks do.  Let me know if I can assist.

**Comment by luckedea** [comment]
Same problem with 21.1
