### ISSUE TITLE
Submit Extension-AccessOwnership

### ISSUE THREAD

**Issue by Lennong** [nzbgetcom/nzbget#322]
### Is there already an issue for this request?

- [X] I have checked older issues, open and closed

### Describe your issue

I have written a small extension as for modify / set access, uid and gid on the downloads. This came about as the old script stopped working when the development fired up again (which is great!).

If any of you wanna have a look-see if it is up to par and / or give me a fork to drop it in?

https://github.com/Lennong/Extension-AccessOwnership

**Comment by dnzbk** [comment]
Thanks for the really useful extension. 

We've created a [fork](https://github.com/nzbgetcom/Extension-AccessOwnership) of your repository - feel free to use it.
We've also added pipelines for releases and for testing.

A few improvements worth adding:
1. Validation for invalid data, such as negative numbers, at least;
2. Tests. [Here's](https://github.com/nzbgetcom/Extension-ExtendedUnrar/blob/main/tests.py) an example;
3. Change the extension version from "1.0.0" to "1.0".

**Comment by Lennong** [comment]
Points 1 and 3 has been adressed. Point 3 however will be on the backburner..

Became a bit annoyed with the workflow scripts throwing errors for each commit I made so I threw that out. Did a pull request so you can have a look-se and such.

**Comment by dnzbk** [comment]
Made the [release](https://github.com/nzbgetcom/Extension-AccessOwnership/releases/tag/v1.2).
The issue can be closed now, I suppose.
