### ISSUE TITLE
Doc: listgroups mentions sizes in megabytes although the API returns mebibytes

### ISSUE THREAD

**Issue by sbraz** [nzbgetcom/nzbget#327]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### NZBGet Version

v24.1-stable

### Platform

All

### Environment

```markdown
Not relevant
```

### Current Behavior

Here, we see the API returns a value un MiB, not MB:
https://github.com/nzbgetcom/nzbget/blob/2a5418566531b2d998c1dc7d120612020890f554/daemon/remote/XmlRpc.cpp#L1802
The documentation states that values are in megabytes: https://nzbget.com/documentation/api/listgroups/

### Expected Behavior

The documentation should clearly state that the value is in mebibytes, not megabytes.

### Extra information

I couldn't find the source for https://nzbget.com/, is it public at the moment?

**Comment by luckedea** [comment]
@sbraz No, website isn't public at the moment and going through old documentation is WIP (sigh).
The desire here is to push all technical information into github, sorry for a bit of inconsistency. 

Thank you for bringing this up, I'll get it all correctly reflected soon, no need for PR.
