### ISSUE TITLE
Build faluire on Banana Pi BPI-M1

### ISSUE THREAD

**Issue by Prinz23** [nzbgetcom/nzbget#347]
### NZBGet Version

v24.3-testing

### Platform

Linux/Docker

### Environment

```markdown
Device: Banana Pi BPI-M1
OS: Armbian 23.02.2 Buster
```

### Problem or Question

The compiling seams to fail since the release of 24.2 and to be related to the new System Info.

### Steps To Reproduce

mkdir build
cd build
cmake ..
cmake --build . -j 2

### Logs

[ 98%] Building CXX object CMakeFiles/nzbget.dir/daemon/system/CPU.cpp.o
/home/nzbgetcom/daemon/system/SystemInfo.cpp: In member function void System::SystemInfo::InitLibsInfo():
/home/nzbgetcom/daemon/system/SystemInfo.cpp:72:38: error: OPENSSL_FULL_VERSION_STR was not declared in this scope
   m_libraries.push_back({ "OpenSSL", OPENSSL_FULL_VERSION_STR });
                                      ^~~~~~~~~~~~~~~~~~~~~~~~
/home/nzbgetcom/daemon/system/SystemInfo.cpp:72:38: note: suggested alternative: OPENSSL_VERSION
   m_libraries.push_back({ "OpenSSL", OPENSSL_FULL_VERSION_STR });
                                      ^~~~~~~~~~~~~~~~~~~~~~~~
                                      OPENSSL_VERSION
/home/nzbgetcom/daemon/system/SystemInfo.cpp:72:64: error: no matching function for call to std::vector<System::Library>::push_back(<brace-enclosed initializer list>)
   m_libraries.push_back({ "OpenSSL", OPENSSL_FULL_VERSION_STR });
                                                                ^
In file included from /usr/include/c++/8/vector:64,
                 from /home/nzbgetcom/daemon/main/nzbget.h:207,
                 from /home/nzbgetcom/daemon/system/SystemInfo.cpp:20:
/usr/include/c++/8/bits/stl_vector.h:1074:7: note: candidate: void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = System::Library; _Alloc = std::allocator<System::Library>; std::vector<_Tp, _Alloc>::value_type = System::Library]
       push_back(const value_type& __x)
       ^~~~~~~~~
/usr/include/c++/8/bits/stl_vector.h:1074:7: note:   no known conversion for argument 1 from <brace-enclosed initializer list> to const value_type& {aka const System::Library&}
/usr/include/c++/8/bits/stl_vector.h:1090:7: note: candidate: void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = System::Library; _Alloc = std::allocator<System::Library>; std::vector<_Tp, _Alloc>::value_type = System::Library]
       push_back(value_type&& __x)
       ^~~~~~~~~
/usr/include/c++/8/bits/stl_vector.h:1090:7: note:   no known conversion for argument 1 from <brace-enclosed initializer list> to std::vector<System::Library>::value_type&& {aka System::Library&&}
In file included from /home/nzbgetcom/daemon/util/FileSystem.h:28,
                 from /home/nzbgetcom/daemon/system/CPU.cpp:26:
/home/nzbgetcom/daemon/main/Options.h: In member function virtual void Options::Extender::AddFeed(int, const char*, const char*, int, const char*, bool, bool, const char*, int, const char*):
/home/nzbgetcom/daemon/main/Options.h:180:28: warning: unused parameter id [-Wunused-parameter]
   virtual void AddFeed(int id, const char* name, const char* url, int interval,
                        ~~~~^~
/home/nzbgetcom/daemon/main/Options.h:180:44: warning: unused parameter name [-Wunused-parameter]
   virtual void AddFeed(int id, const char* name, const char* url, int interval,
                                ~~~~~~~~~~~~^~~~
/home/nzbgetcom/daemon/main/Options.h:180:62: warning: unused parameter url [-Wunused-parameter]
   virtual void AddFeed(int id, const char* name, const char* url, int interval,
                                                  ~~~~~~~~~~~~^~~
/home/nzbgetcom/daemon/main/Options.h:180:71: warning: unused parameter interval [-Wunused-parameter]
   virtual void AddFeed(int id, const char* name, const char* url, int interval,
                                                                   ~~~~^~~~~~~~
/home/nzbgetcom/daemon/main/Options.h:181:16: warning: unused parameter filter [-Wunused-parameter]
    const char* filter, bool backlog, bool pauseNzb, const char* category,
    ~~~~~~~~~~~~^~~~~~
/home/nzbgetcom/daemon/main/Options.h:181:29: warning: unused parameter backlog [-Wunused-parameter]
    const char* filter, bool backlog, bool pauseNzb, const char* category,
                        ~~~~~^~~~~~~
/home/nzbgetcom/daemon/main/Options.h:181:43: warning: unused parameter pauseNzb [-Wunused-parameter]
    const char* filter, bool backlog, bool pauseNzb, const char* category,
                                      ~~~~~^~~~~~~~
/home/nzbgetcom/daemon/main/Options.h:181:65: warning: unused parameter category [-Wunused-parameter]
    const char* filter, bool backlog, bool pauseNzb, const char* category,
                                                     ~~~~~~~~~~~~^~~~~~~~
/home/nzbgetcom/daemon/main/Options.h:182:8: warning: unused parameter priority [-Wunused-parameter]
    int priority, const char* extensions) {}
    ~~~~^~~~~~~~
/home/nzbgetcom/daemon/main/Options.h:182:30: warning: unused parameter extensions [-Wunused-parameter]
    int priority, const char* extensions) {}
                  ~~~~~~~~~~~~^~~~~~~~~~
/home/nzbgetcom/daemon/main/Options.h: In member function virtual void Options::Extender::AddTask(int, int, int, int, Options::ESchedulerCommand, const char*):
/home/nzbgetcom/daemon/main/Options.h:183:28: warning: unused parameter id [-Wunused-parameter]
   virtual void AddTask(int id, int hours, int minutes, int weekDaysBits, ESchedulerCommand command,
                        ~~~~^~
/home/nzbgetcom/daemon/main/Options.h:183:36: warning: unused parameter hours [-Wunused-parameter]
   virtual void AddTask(int id, int hours, int minutes, int weekDaysBits, ESchedulerCommand command,
                                ~~~~^~~~~
/home/nzbgetcom/daemon/main/Options.h:183:47: warning: unused parameter minutes [-Wunused-parameter]
   virtual void AddTask(int id, int hours, int minutes, int weekDaysBits, ESchedulerCommand command,
                                           ~~~~^~~~~~~
/home/nzbgetcom/daemon/main/Options.h:183:60: warning: unused parameter weekDaysBits [-Wunused-parameter]
   virtual void AddTask(int id, int hours, int minutes, int weekDaysBits, ESchedulerCommand command,
                                                        ~~~~^~~~~~~~~~~~
/home/nzbgetcom/daemon/main/Options.h:183:92: warning: unused parameter command [-Wunused-parameter]
   virtual void AddTask(int id, int hours, int minutes, int weekDaysBits, ESchedulerCommand command,
                                                                          ~~~~~~~~~~~~~~~~~~^~~~~~~
/home/nzbgetcom/daemon/main/Options.h:184:16: warning: unused parameter param [-Wunused-parameter]
    const char* param) {}
    ~~~~~~~~~~~~^~~~~
make[2]: *** [CMakeFiles/nzbget.dir/build.make:1210: CMakeFiles/nzbget.dir/daemon/system/SystemInfo.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:94: CMakeFiles/nzbget.dir/all] Error 2
make: *** [Makefile:136: all] Error 2


### Extra information

_No response_

**Comment by dnzbk** [comment]
What version of OpenSSL are you using?
Anyway, I should have added an additional check for OPENSSL_FULL_VERSION_STR.
Not all versions of OpenSSL have  OPENSSL_FULL_VERSION_STR, as I can see now.
For a quick fix, you can replace OPENSSL_FULL_VERSION_STR with OPENSSL_VERSION and everything should be fine.

**Comment by dnzbk** [comment]
Got it, thanks.

**Comment by dnzbk** [comment]
Should be fixed now. 
Could you also check [NZBGet installer](https://nzbget.com/download/)? Would it work on your system?

**Comment by Prinz23** [comment]
Yes, nzbget builds now again.

The installer armhf version also runs on my BPi, but i prefer the native build version.

**Comment by dnzbk** [comment]
Thank you!
