### ISSUE TITLE
Qnap X41 Version Files corrupted not playable

### ISSUE THREAD

**Issue by kogomonier** [nzbgetcom/nzbget#352]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### NZBGet Version

v24.2-stable

### Platform

All

### Environment

```markdown
Qnap TS-231P, Firmware QTS 5.1.8.2823 

Had NZBget 24.1 installed, thought release note "fixed NZB generator: the last segment was incorrect" will fix issue and upgraded to nzbget_24.2_arm-x41.qpkg. Issue still the same
```

### Current Behavior

I download different files (mainly currently related movies) and after unpacking the files are corrupted and not playable via plex or even VLC. Bitrate and informations in mkv container are defective.

### Expected Behavior

Non corrupted files after unpacking. I tested the same nzb with the Windows Version of NZBget Version 21.1 and everything is perfectly fine as it should be

### Extra information

![image](https://github.com/user-attachments/assets/13995aeb-ca5e-41b7-9335-21aa129d7be5)

**Comment by dnzbk** [comment]
"fixed NZB generator: the last segment was incorrect"  -  doesn't relate to this issue. There was a bug in the NZB generator that was not correctly counting the size of the last segment, and which is used by the local NZBGet NNTP server mainly for testing.

May I clarify a few things:
Do I understand correctly that this bug only occurs on QNAP? 
Does v21.1 work correctly on QNAP?
Do you have any problems with v24.2 on other systems?
Could you send the problematic nzb file to my [email](denis@nzbget.com)? I'd like to test it.

Thank you.

**Comment by luckedea** [comment]
Most likely https://github.com/nzbgetcom/nzbget/issues/358 is related.

**Comment by luckedea** [comment]
@kogomonier While we are working on this, as a temporary solution - you can disable DirectWrite on your instance.
