### ISSUE TITLE
DirectWrite enable causes file corruption on big files

### ISSUE THREAD

**Issue by H34dl3ss** [nzbgetcom/nzbget#358]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### NZBGet Version

v24.1-stable

### Platform

Linux/Docker

### Environment

```markdown
Docker container
ghcr.io/nzbgetcom/nzbget:latest (by that time it was 24.1)

OS Information 	linux aarch64 Raspbian GNU/Linux 10 (buster)
Kernel Version 	5.10.103-v8+
Total CPU 	4
Total memory 	3.9 GB

The same issue occured on docker version 21.1 (linuxserver/nzbget:latest) but since they seized the armhf platform yours is the only docker I can use without switching the OS.
```

### Current Behavior

When loading files >2.6GB the resulting file on the disk will be zeroes above 2.6GB.
After setting DirectWrite to NO, the resulting file is good.

### Expected Behavior

Download intact files XD

### Logs

Not sure where to look for proper log files.
Awaiting instructions then I can deliver.

**Comment by dnzbk** [comment]
@H34dl3ss 
Working on this one. As a temporary solution, disabling `DirectWrite` should fix the issue.
