### ISSUE TITLE
QNAP: unable to start daemon "invalid DaemonUsername" 

### ISSUE THREAD

**Issue by OneCDOnly** [nzbgetcom/nzbget#390]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### NZBGet Version

v24.3-stable

### Platform

NAS/Synology/QNAP

### Environment

```markdown
QNAP NAS (TS-251+) running QTS 5.1.8 firmware (QNAP customised Linux kernel)
```

### Current Behavior

When starting daemon: 
```
/etc/init.d/nzbget.sh start
```
... nothing appears in terminal to advise of errors or otherwise.  Daemon process is not running.

Checked nzbget logs, and saw this:
```
Fri Sep 13 06:29:22 2024	ERROR	Starting daemon failed: invalid DaemonUsername
Fri Sep 13 06:29:22 2024	INFO	Deleting lock file
```

### Expected Behavior

For daemon to start.  🤓

If I alter the `nzbget.conf.qnap` file and change the value of 'DaemonUsername' from `root` to `admin`, I can then start the service. 

### Extra information

In QNAP QTS, `admin` is the root user (UID=0). 

I'm also not sure why this username needs to be specified. If executing process as UID/EUID = 0, it's easy to find current username. Maybe the test should be for UID instead of the literal username? 

Thoughts?

**Comment by luckedea** [comment]
@OneCDOnly 🐛

**Comment by dnzbk** [comment]
@OneCDOnly 
We have reposted qpkgs v24.3 with a fix - could you try them out?

**Comment by OneCDOnly** [comment]
@dnzbk fast work! 👍🏽 

Fix confirmed, thank you. 🤓
