### ISSUE TITLE
100% cpu usage when encountering "430 no such article" errors

### ISSUE THREAD

**Issue by gdark3** [nzbgetcom/nzbget#396]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### NZBGet Version

v24.3-stable

### Platform

Windows

### Environment

```markdown
OS	Windows 10 22H2 (19045)
CPU	13th Gen Intel(R) Core(TM) i9-13900KF
Arch	x86_64

Name	Version	Path
Python	3.11.2
Libraries
Name	Version
LibXML2	2.11.6
Gzip	1.3.0
OpenSSL	3.1.4
Boost	1_83
```

### Current Behavior

When an article produces error logs like 430 no such article, there is no download happening the nzbget button is circling green, and the cpu usage spikes to 100% as it trys all the servers but cant do to the 430 no such article.
When an article downloads regularly there is no cpu usage, its only when its not downloading anything and encounters this error the spikes happen. Sometimes for large files it lasts several minutes.

### Expected Behavior

No 100% cpu usage ever, i have a decent cpu/gpu. 13900kf + 4090

### Steps To Reproduce

I recently updated to 24.3 from i think 18, which didnt have this issue. Original reason for upgrade was the extension manager integration. Steps to reporiduce are hard because you have to try with a known 430 such article rip. I have 4 indexers and 5 providers.

### Logs

![2](https://github.com/user-attachments/assets/dca74456-457e-4a04-af04-029a5bd3fdc5)
![Capture](https://github.com/user-attachments/assets/96a7024c-ad34-4667-bf3f-0a2ab4914364)

**Comment by dnzbk** [comment]
Confirmed. Related to #300.

**Comment by gdark3** [comment]
I downgraded to nzbget.net 21.1 stable and issue went away. Was getting almost 50% 430 no such articles erros on 24.3 and 23 and 22, for some reason, and then when i downgraded i tried the same nzbs again and it grabbed them with ease. 

Only issue with 21.1 is FakeDetector doesnt seem to work with manual script add

**Comment by dnzbk** [comment]
Could you give me those nzbs so I can try them out? 
denis@nzbget.com

**Comment by gdark3** [comment]
> Could you give me those nzbs so I can try them out? [denis@nzbget.com](mailto:denis@nzbget.com)

I edited the comment, the nzbs downloaded fine when i swapped vpns. Keeping this thread on-topic for the 100% cpu usage for versions > 21.1 which is still occurring. I will stay on 21.1 for now until the cpu usage or memory leak is fixed.
