### ISSUE TITLE
Installing 24.3 via WebUI on Synology fails with errors

### ISSUE THREAD

**Issue by drahamim** [nzbgetcom/nzbget#399]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### NZBGet Version

v24.3-stable

### Platform

NAS/Synology/QNAP

### Environment

```markdown
Version	24.2
Config path	/volume1/@appstore/nzbget/var/nzbget.conf
Tools
Name	Version	Path
Python	2.7.18	/bin/python
7-Zip	24.05	/volume1/@appstore/nzbget/bin/7za
UnRAR	5.21	/usr/bin/unrar


System
OS	GNU/Linux 4.4.59+ (DSM 6.2.4-25556 Update 7)
CPU	Intel(R) Atom(TM) CPU C3538 @ 2.10GHz
Arch	x86_64
Article Cache	100 MB

Libraries
Name	Version
LibXML2	2.12.4
ncurses	6.4
Gzip	1.3.1
OpenSSL	3.1.2
Boost	1_84
```

### Current Behavior

I get a list of errors regarding directory settings. 
```Invalid value for option "<some>Dir" (.../@appstore/nzbget/bin/downloads/nzb) error 13``` I have checked permissions over and over and its still failing

### Expected Behavior

Update NzbGet

### Steps To Reproduce

1. run Nzbget 24.2 installed via SynoCommunity.
2. configure "MainDir" to a directory outside the @appstore path. 
3. attempt update.

### Logs

Executing update-script /volume1/@appstore/nzbget/bin/install-update.sh
Downloading version information...
nzbget.conf(55): Invalid value for option "TempDir" (/volume1/@appstore/nzbget/bin/downloads/tmp): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/tmp: errno 13, Permission denied
nzbget.conf(52): Invalid value for option "QueueDir" (/volume1/@appstore/nzbget/bin/downloads/queue): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/queue: errno 13, Permission denied
nzbget.conf(46): Invalid value for option "NzbDir" (/volume1/@appstore/nzbget/bin/downloads/nzb): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/nzb: errno 13, Permission denied
Downloading verification signature...
nzbget.conf(55): Invalid value for option "TempDir" (/volume1/@appstore/nzbget/bin/downloads/tmp): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/tmp: errno 13, Permission denied
nzbget.conf(52): Invalid value for option "QueueDir" (/volume1/@appstore/nzbget/bin/downloads/queue): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/queue: errno 13, Permission denied
nzbget.conf(46): Invalid value for option "NzbDir" (/volume1/@appstore/nzbget/bin/downloads/nzb): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/nzb: errno 13, Permission denied
Downloading nzbget-24.3-bin-linux.run...
nzbget.conf(55): Invalid value for option "TempDir" (/volume1/@appstore/nzbget/bin/downloads/tmp): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/tmp: errno 13, Permission denied
nzbget.conf(52): Invalid value for option "QueueDir" (/volume1/@appstore/nzbget/bin/downloads/queue): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/queue: errno 13, Permission denied
nzbget.conf(46): Invalid value for option "NzbDir" (/volume1/@appstore/nzbget/bin/downloads/nzb): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/nzb: errno 13, Permission denied
Verifying package authenticity...
nzbget.conf(55): Invalid value for option "TempDir" (/volume1/@appstore/nzbget/bin/downloads/tmp): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/tmp: errno 13, Permission denied
nzbget.conf(52): Invalid value for option "QueueDir" (/volume1/@appstore/nzbget/bin/downloads/queue): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/queue: errno 13, Permission denied
nzbget.conf(46): Invalid value for option "NzbDir" (/volume1/@appstore/nzbget/bin/downloads/nzb): could not read information for directory /volume1/@appstore/nzbget/bin/downloads/nzb: errno 13, Permission denied
Updating NZBGet...
...
Installer for nzbget-24.3
Verifying package...
Checking system...
CPU-Architecture: x86_64
Unpacking...
/volume1/Storage/Public/Videos/Download/Usenet/NZBget/tmp/nzbget-24.3-bin-linux.run: line 258: /volume1/@appstore/nzbget/bin/installer.tmp: Permission denied
Update failed, installer terminated with error status

**Comment by phnzb** [comment]
@drahamim
Synology DSM runs each package under a specific user. For SynoCommunity nzbget package, `sc-nzbget` user is used.
When the SynoCommunity nzbget package is installed, you select a shared folder to save the nzbget files. The default is `downloads`. All permissions to this folder will be automatically created during installation.
If you want to use a different shared folder for nzbget files, you need to add RW permissions for this folder for the `sc-nzbget` user via:
Control Panel -> Shared Folder -> Select folder you want to use -> Edit -> Permissions tab -> select from combobox `System internal user` -> sc-nzbget -> Read/Write -> Save.
I just tested on DS215j / DSM 6.2.4-25556 Update 7
- Installed the stable version v24.3
- Added permission to the new folder
- Restarted the nzbget package from the Package Center
- Update to v24.3-testing was successful

**Comment by drahamim** [comment]
After following as you suggested above I still get the  permission denied response. 

Should I try re-installing 24.2 or just remove and install with 24.3?

**Comment by phnzb** [comment]
@drahamim 

1. Can I assume that nzbget 24.2 is working fine and the problem only occurs during the update?
2. With the default settings, MainDir in the SynoCommunity package is always outside the @appstore path. By default MainDir is the path to the volume selected during installation (/volume1/downloads), so if you change MainDir then only one thing is required for correct work - permissions to the changed volume, as I wrote before.
3. In your case it might be a bug caused by some inconsistency in path settings. If you share your nzbget.conf, we will look into the issue deeper. On Synology, you can backup nzbget.conf via WebUI - Settings - SYSTEM - Backup settings. Remove any sensitive information (news server information, etc.) from the conf file and send it to nzbget@nzbget.com
4. As a last resort, you can uninstall the nzbget package and reinstall it via SynoCommunity. Please note: this will install the latest version (you cannot roll back to 24.2), and all settings will be reset to defaults. If you want to keep your settings, you can backup nzbget.conf (see above) and restore it after reinstallation (via WebUI - Settings - SYSTEM - Restore Settings).

**Comment by drahamim** [comment]
1. I have been trying to update as I've been seeing issues lately with unpack failures with little to no clarity as to what the cause maybe. Usually an update tends to fix these issues. 
2. I change it to a sub directory in /volume1/ 
3. I will send it and put this ticket number into the email subject.

**Comment by drahamim** [comment]
Sigh.... This issue can be closed.

on a hail-marry i changed my uMask setting to `1000` instead of `0777` or `777`

That seems to have fixed my downloads and the update script.
