### ISSUE TITLE
Why isn't this a direct fork of nzbget/nzbget?

### ISSUE THREAD

**Issue by fabiorzfreitas** [nzbgetcom/nzbget#43]
Both this repo and its organization were created only a few months ago, and while I make no accusation, I only found out about this project from a discussion somewhere else. I've found no mention of it on [/r/nzbget](https://reddit.com/r/nzbget), or in the (dead) forums.

I'm not actively keeping an eye on what's been happening with NZBGet as a whole, but I figured I should at least raise a question.

**Comment by luckedea** [comment]
This is the way I initially organized it: instead of forking, I recreated the repository. Now the apps are rebuilt, and our intentions are to provide support for it.

This is a passion project, it's a great suggestion to make a Reddit announcement, thank you.

**Comment by luckedea** [comment]
Reddit post https://www.reddit.com/r/usenet/comments/17k0tda/new_nzbget_project/
Going to close this issue.

**Comment by paul-chambers** [comment]
For some reason, GitHub won't list the forks of a repo when you search for it, irrespective of how many stars it might have. So in at least that respect, it was smart to divorce your repo from hugbug's archived one. 

Searching for 'nzbget' on github will show `nzbget/nzbget` and `nzbgetcom/nzbget`, but `nzbget-ng/nzbget` isn't listed.
