### ISSUE TITLE
Is there a docker container?

### ISSUE THREAD

**Issue by famewolf** [nzbgetcom/nzbget#44]
As the subject indicates....is a docker container available that I can switch to from the last nzbget/nbzget to get the newest fixes?

**Comment by luckedea** [comment]
Not yet, with a lot of interest to docker-based setups, I'll work on this in higher priority. Stay tuned.

**Comment by johnmmcgee** [comment]
2nd this.  would love to see it.

**Comment by luckedea** [comment]
Our own image is already published here under Packages and on Dockerhub replacing linuxserver's project. 
Just doing more testing as we can today.

Stay tuned!

**Comment by phnzb** [comment]
Feel free to download and test docker images !
https://hub.docker.com/r/nzbgetcom/nzbget  / https://github.com/nzbgetcom/nzbget/pkgs/container/nzbget
Docker Hub readme have all needeed info. Known limitations - we bundle docker image with Python 3.11 and some extension does not support Python 3.10+. Fixes will be available soon!
