### ISSUE TITLE
Change the default branch to nzbget for par2cmdline-turbo

### ISSUE THREAD

**Issue by sbraz** [nzbgetcom/nzbget#458]
### NZBGet Version

v24.5-stable

### Platform

All

### Environment

```markdown
N/A
```

### Problem or Question

Hi,
I initially thought https://github.com/nzbgetcom/par2cmdline-turbo contained no changes compared to https://github.com/animetosho/par2cmdline-turbo/. Could you please change the default branch to nzbget on GitHub for everyone to see that it does have differences?

**Comment by dnzbk** [comment]
Done
