### ISSUE TITLE
Synology DSM support

### ISSUE THREAD

**Issue by luckedea** [nzbgetcom/nzbget#46]
There are requests from reddit/community about Synology DSM app

https://www.reddit.com/r/usenet/comments/17k0tda/comment/k758cwq/
https://www.reddit.com/r/usenet/comments/17k0tda/comment/k750nq6/

Creating an issue to put this on radar.

**Comment by Safihre** [comment]
You can just copy the already available package at SynoCommunity: it just downloads the Linux release and installs it, no custom compilation for all the weird Synology platforms etc. 
You would just have to change your URL's/name and you're good to go.
It also allows the internal auto-updater to work, so you just have to create this package only once.
You can create a PR and the SynoCommunity people will publish it for you in their repository.

I made that package a few years ago.

**Comment by arsMatrix** [comment]
Will this be published on the SynoCommunity repository?

**Comment by luckedea** [comment]
@arsMatrix Absolutely, yes.

**Comment by Safihre** [comment]
You made your own spk build pipeline instead of using the SynoCommunity one, how do you expect it to be included in SynoCommunity?
That's not how it works..

**Comment by luckedea** [comment]
@Safihre Of course. We plan to maintain both (.spk and SynoCommunity).

spk step was needed to learn more about Synology builds and test it more.
SynoCommunity path needs:
- A PR into the code you committed (if they would allow us to just override nzbget.net build?)
- More testing for upgrades of existing customers. This isn't a concern with a new .SPK
- And ideally more updates to extensions to come along (which is what the main focus of development is at the moment)

It's definitely coming up soon.

**Comment by Thaek** [comment]
It says DSM 7.x on the website, will those SPK work with my DSM 6 NAS?

**Comment by luckedea** [comment]
@Thaek unfortunately no, new SPKs are only for 7.x.+

Your options are:
1. Older versions (v21 and older)
2. Docker
3. Or wait for us to complete the SynoCommunity submission - we are working on it.

**Comment by luckedea** [comment]
@Safihre Oh absolutely would love (and need) your assistance with SynoCommunity - it's something @phnzb is picking up next.

I partially answered your question in https://github.com/nzbgetcom/nzbget/issues/46#issuecomment-1864994211 - we wanted to learn Synology builds. Unfortunately while learning we noticed crashes of old packages on _some_ devices, so the reason was "Ok, it's not as simple as it looks, let us build SPKs first and test it better first". Hope that makes sense.

**Comment by Thaek** [comment]
I installed the normal Linux Build on my DSM 6.x Synology and it works perfectly fine. Thanks!

**Comment by luckedea** [comment]
Thank you @Safihre for assisting with SynoCommunity support.
Tested on multiple device - it looks great. Installs, updates, updates from nzbget v21, all looks smooth.

We now support it from all angles - synocommunity, spk, docker, .run, you name it :) 

Going to close this to entice new reports from users if any.
