### ISSUE TITLE
ninja: error: 'par2-turbo/src/par2-turbo-build/libpar2-turbo.a'

### ISSUE THREAD

**Issue by dnzbk** [nzbgetcom/nzbget#460]
### NZBGet Version

v24.5-stable

### Platform

All

### Environment

```markdown
Any
```

### Problem or Question

After switching to ExternalProject_Add from FetchContent in v24.5, the cmake Ninja generator started working incorrectly. Probably other non-default generators as well.

### Logs

cmake --build .
ninja: error: 'par2-turbo/src/par2-turbo-build/libpar2-turbo.a', needed by 'nzbget', missing and no known rule to make it
de

**Comment by sbraz** [comment]
Hi @dnzbk, I just hit this on Gentoo because our build was using ninja. One answer [here](https://stackoverflow.com/questions/54866067/cmake-and-ninja-missing-and-no-known-rule-to-make-it) mentions `BUILD_BYPRODUCTS`?

**Comment by dnzbk** [comment]
Hi, @sbraz  
Yeah, I’ve seen that, thank you, but I just didn’t find some time to try that out yet.
