### ISSUE TITLE
Add aarch64 builds to CI

### ISSUE THREAD

**Issue by MichaIng** [nzbgetcom/nzbget#57]
Is there a particular reason why `aarch64` binaries are not built? As far as I can see, the [build scripts](https://github.com/nzbgetcom/nzbget/blob/develop/linux/build-nzbget) do still support it, so it might be possible to just add it here: https://github.com/nzbgetcom/nzbget/blob/develop/.github/workflows/linux.yml#L26

But the `build-nzbget-ci.sh` is not public, so not sure whether it is an entirely different script.

**Comment by phnzb** [comment]
I can try building it, but I'll need someone's help testing it

**Comment by MichaIng** [comment]
That would be great, I can test it.

**Comment by phnzb** [comment]
@MichaIng I have successfully build aarch64 toolchain and nzbget for this architecture. Please try to test aarch64 build from [this workflow](https://github.com/nzbgetcom/nzbget/actions/runs/6903881558) [artifacts](https://github.com/nzbgetcom/nzbget/suites/18281080799/artifacts/1057020077).If everything is ok, we will add aarch64 to the CI builds.

**Comment by MichaIng** [comment]
Works like a charm, tested on NanoPi R4S. Many thanks for adding it so quickly 🚀.

**Comment by phnzb** [comment]
@MichaIng PR with added aarch64 builds was merged into develop #61 . Next linux CI builds will contain aarch64 architecture. Also, 22.0 release was updated with linux builds with aarch64 support. Please test if possible.

**Comment by MichaIng** [comment]
Works very well with the 22.0 release. Here a test install in GitHub actions, within QEMU-emulated container: https://github.com/MichaIng/DietPi/actions/runs/6932552257/job/18856975756#step:2:655
Some lines down the output, it is also tested whether the service is running and the expected TCP port ist listened to.

This includes already running it via systemd service with `-so OutputMode=log` 🙂.

I also did another successful test install on the NanoPi R4S.
