### ISSUE TITLE
Linux installer download URL in docs currently does not exist

### ISSUE THREAD

**Issue by MichaIng** [nzbgetcom/nzbget#58]
The [docs](https://nzbget.com/documentation/installation-on-linux/) currently state https://nzbget.com/download/nzbget-latest-bin-linux.run as URL for the installer, which would be a directly replacement for the `nzbget.net` URL of the original project. Is this intended to work at some point (pointing to the latest release asset released on GitHub)?

We have a scripted installation option in our distro, and would like to migrate to your fork, hence I am asking: https://github.com/MichaIng/DietPi/pull/6752
We could also obtain the latest asset from https://api.github.com/repos/nzbgetcom/nzbget/releases/latest, but it means one network request more 😉.

**Comment by phnzb** [comment]
@MichaIng website redirect was added to nzbget.com. You can now use https://nzbget.com/download/nzbget-latest-bin-linux.run as replacement of old link.

**Comment by MichaIng** [comment]
Ah that is great. Many thanks!
