### ISSUE TITLE
Allow to run server in systemd-friendly foreground mode

### ISSUE THREAD

**Issue by MichaIng** [nzbgetcom/nzbget#59]
Currently, NZBGet can run either in interactive console foreground mode (`-s`) or in background/daemon mode (`-D`). When using systemd, best would be to run the process in foreground, but without an interactive console. This way the process status as well as potentially STDOUT/STDERR can be directly monitored via `systemctl status nzbget`/`journalctl -u nzbget` (with the unit file named `nzbget.service`). Currently one needs to use `Type=forking` in which case the process is not directly attached to/monitored by systemd.

For perfect setup as systemd service, two things would be great:
1. A foreground server mode, i.e. like `-D` but without forking the process into background.
2. An option to log to STDOUT instead of a log file, for full `systemd-journald` integration, i.e. no plain text log files, and combined wrapping service + process logs via `journalctl -u nzbget`.

Consider this a low priority request, as it works just well with `Type=forking` and a log file, of course, which matches the way it needs to be done with SysV.

**Comment by phnzb** [comment]
@MichaIng this can be achieved with current nzbget with `-o OutputMode=log -o WriteLog=none`
nzbget.service example
```
[Unit]
Description=NZBGet service
After=network.target

[Service]
Type=simple
WorkingDirectory=/home/user/nzbget
ExecStart=/home/user/nzbget/nzbget -s -c /home/user/nzbget/nzbget.conf -o OutputMode=log -o WriteLog=none
ExecStop=/home/user/nzbget/nzbget -Q
Restart=always
User=user
Group=user

[Install]
WantedBy=multi-user.target
```

**Comment by MichaIng** [comment]
Ah nice, many thanks, I missed the `OutputMode` option. The sample says the value should be `loggable`, is `log` a short form (verified that both work)?

Does `nzbget -Q` do anything in addition to what is done when sending SIGTERM (what systemd does by default)? At least without the `ExecStop` command, I see the log entry for a regular shutdown:
```
nzbget[860]: [INFO] Stopping, please wait...
```

**Comment by phnzb** [comment]
@MichaIng 
1. You can use for loggable OutputMode ([source](https://github.com/nzbgetcom/nzbget/blob/85645ad0843750050695d0d6f58d7a1675402d90/daemon/main/Options.cpp#L767C7-L767C7)):
- loggable
- logable
- log
2. nzbget handles SIGKILL correctly, so ExecStop can be removed from unit.

**Comment by MichaIng** [comment]
Many thanks, works great, hence closing this.
