### ISSUE TITLE
Include VideoSort by default

### ISSUE THREAD

**Issue by francislavoie** [nzbgetcom/nzbget#60]
It would be great if https://github.com/nzbget/VideoSort was shipped by default.

I've been using this script for a very long time, it's essential to make sure I have filenames that are sensible, instead of filenames with hashes.

I'm running Python 3.12 on my Windows system (because that's the version `scoop install python` installed) and it was no longer working as is so I had to make some minor code changes for compatibility. Here's a patch with the changes that work for me (apply to VideoSort's latest release)

[videosort.patch](https://github.com/nzbgetcom/nzbget/files/13399222/5f4c5e.-.c76289.patch)

**Comment by francislavoie** [comment]
I'm pretty sure I made those changes against `master`. Maybe I'm wrong, it's been a couple months since I did it, just thought of it again this weekend.

Looking forwards to it! Still running old nzbget for now but I'll make the switch soon probably.

**Comment by luckedea** [comment]
@francislavoie Sorry, I phrased it incorrectly. I meant that we deviated from old `master` already to get it working with newer versions of Python too.

**Comment by dnzbk** [comment]
@francislavoie Thank you for sharing your patch.
VideoSport is now compatible with Python 3.12.
I also updated the dependencies to the actual versions.
It would be great if you could try our version on your setup too and provide some feedback.
[Release 9.0](https://github.com/nzbgetcom/Extension-VideoSort/releases/tag/v9.0)

**Comment by francislavoie** [comment]
Finally got around to installing the new nzbget testing version + the updated videosort script, all seems to work well!
