### ISSUE TITLE
Script support (PasswordDetector, ExtendedUnrar, and EasySort)

### ISSUE THREAD

**Issue by rEes9P** [nzbgetcom/nzbget#66]
I just came across your excellent project that takes @hugbug's work forward and am very glad to have done so. After a long time most of my scripts are working again and I am very excited to read about the upcoming extensions functionality in v23!

While FakeDetector, FailureLink and VideoSort are up and running (thanks to the versions that you have posted) and nzbToMedia and DeleteSamples scripts are working successfully without any changes too, I am still unable to get the following scripts to work and was wondering if you could please shed some light on the issue:

- [PasswordDetector](https://forum.nzbget.net/viewtopic.php?f=8&t=1391&hilit=passworddetector) - Since you have added a working version of FakeDetector it would be great if you could please add this too eventually
- [ExtendedUnrar](https://forum.nzbget.net/viewtopic.php?f=8&t=1690&hilit=extendedunrar&start=20) - Will the functionality offered by this script be baked into NZBGet in the future? If not, and if this script is still necessary, then could you please add a working version as and when possible?
- [EasySort](https://forum.nzbget.net/viewtopic.php?f=8&t=2163&p=23026&hilit=easysort#p23026) - Since you have already posted VideoSort I wondered if this offshoot of it could be offered too

Thanks again for this wonderful effort!

**Comment by luckedea** [comment]
Thanks @rEes9P 
We are working actively on extension for next (v23) update. Revamped 3 "official" extensions, and starting to pick up what we can from https://forum.nzbget.net/viewforum.php?f=8 too - and the plan is to review the most popular ones and bundle them.

@dnzbk Will be looking at the 3 you mention too.

**Comment by Mouton99** [comment]
Of note: I'm running ExtendedUnrar without problems on v22.0 (in docker, using `nzbgetcom/nzbget:latest` image).
I am using [the version posted on Apr. 28 2019](https://forum.nzbget.net/viewtopic.php?f=8&t=1690&hilit=extendedunrar&start=20#p21653).

**Comment by sdburrows** [comment]
> I just came across your excellent project that takes @hugbug's work forward and am very glad to have done so. After a long time most of my scripts are working again and I am very excited to read about the upcoming extensions functionality in v23!
> 
> While FakeDetector, FailureLink and VideoSort are up and running (thanks to the versions that you have posted) and nzbToMedia and DeleteSamples scripts are working successfully without any changes too, I am still unable to get the following scripts to work and was wondering if you could please shed some light on the issue:
> 
> * [PasswordDetector](https://forum.nzbget.net/viewtopic.php?f=8&t=1391&hilit=passworddetector) - Since you have added a working version of FakeDetector it would be great if you could please add this too eventually
> * [ExtendedUnrar](https://forum.nzbget.net/viewtopic.php?f=8&t=1690&hilit=extendedunrar&start=20) - Will the functionality offered by this script be baked into NZBGet in the future? If not, and if this script is still necessary, then could you please add a working version as and when possible?
> * [EasySort](https://forum.nzbget.net/viewtopic.php?f=8&t=2163&p=23026&hilit=easysort#p23026) - Since you have already posted VideoSort I wondered if this offshoot of it could be offered too
> 
> Thanks again for this wonderful effort!

@rEes9P: Where do you download the scripts from? I am using v22 with extension scripts (videosort, fakedetector, failurelink) from original hugbug Github repo and it is not working very well, with all kinds of errors. I am on Windows and running Python 2.7.18. Please advise.

**Comment by rEes9P** [comment]
@sdburrows I'm using the built-in scripts and they work just fine out of the box. I am using Python 3.11.7 though so wonder if your issues are because you are using Python 2. It might be best to open a new issue with more information and the errors you are getting so that the devs/other expert users who are much better at Python than I am can have a look and help you out. Good luck!
