### ISSUE TITLE
VideoSort logs some warning messages (not affecting the result) using Python3.12

### ISSUE THREAD

**Issue by dnzbk** [nzbgetcom/nzbget#71]
Such warnings appeared in the logs using Python3.12 which do not really affect the final result.

INFO    Executing post-process-script VideoSort\VideoSort.py for The.Velveteen.Rabbit.2023.1080p.WEBRip.x265-KONTRAST   
INFO    VideoSort.py:624: SyntaxWarning: invali descape sequence '\:'

Perhaps we are using regex expressions that are deprecated since python3.12.

**Comment by rsporsche** [comment]
Where did you get a VideoSort that works with Python 3.12?

I am using the VideoSort released in 2018 from nzbget/VideoSort and it seems to work after replacing the rebulk and babelfish libraries.. but would be interested to know if there's a maintained version somewhere.

**Comment by sdburrows** [comment]
I am getting messages like below. I think it has something to do with how I put the path within Videosort. How do we fix this? 

```
INFO | Wed Feb 07 2024 17:46:26 | Video Sort: m = re.compile('..*((19\|20)\d\d)').search(title)
-- | -- | --
INFO | Wed Feb 07 2024 17:46:26 | Video Sort: X:\NZBGet\Scripts\VideoSort\main.py:785: SyntaxWarning: invalid escape sequence '\d'
INFO | Wed Feb 07 2024 17:46:26 | Video Sort: m = re.compile('..*(\((19\|20)\d\d\))').search(title)
INFO | Wed Feb 07 2024 17:46:26 | Video Sort: X:\NZBGet\Scripts\VideoSort\main.py:783: SyntaxWarning: invalid escape sequence '\('
INFO | Wed Feb 07 2024 17:46:26 | Video Sort: title = re.sub('[\"\:\?\*\\\/\<\>\\|]', ' ', name)
INFO | Wed Feb 07 2024 17:46:26 | Video Sort: X:\NZBGet\Scripts\VideoSort\main.py:380: SyntaxWarning: invalid escape sequence '\:'
```

**Comment by MattPark** [comment]
This is the one I've been using and it appears to be somewhat maintained: https://github.com/theuema/VideoSort

**Comment by dnzbk** [comment]
@sdburrows @MattPark 

VideoSort should be fixed now.
Сonsider upgrading to v10.1 using Extension Manager, thanks.
