### ISSUE TITLE
7za link not working

### ISSUE THREAD

**Issue by nismanoku** [nzbgetcom/nzbget#77]
I installed the docker version and NZBget doesn't find 7za.

the link in the webui ${AppDir}/7za links to /usr/bin/7za > there is no 7za only 7z that is linked to 7zz

corrected the webui to ${AppDir}/7z and added a link to /usr/bin/7z and it works

**Comment by luckedea** [comment]
Thank you, I confirm the problem, working on the fix.

**Comment by woiza** [comment]
What version do use? Since 21.01 alpha, 7zip supports _"using hardware CPU instructions for AES, CRC-32, SHA-1 and SHA-256"_ (game changer!):

https://7-zip.org/history.txt

**Comment by phnzb** [comment]
Fixed in current testing images

**Comment by heartbleeded** [comment]
@phnzb docker images `latest` and `testing` both still have broken `7za`
