### ISSUE TITLE
Docker image: 7zip instead of p7zip 

### ISSUE THREAD

**Issue by woiza** [nzbgetcom/nzbget#81]
I noticed you use p7zip in your docker image. Any chance you could switch to 7zip?
7zip supports hardware optimizations for en- and decryption:

- https://github.com/p7zip-project/p7zip/issues/217 (no one works on p7zip anymore)
- https://7-zip.org/history.txt (21.01 alpha    2021-03-09 for ARM64 and 19.02 alpha    2019-09-05 for Intel/AMD)

Since 7zip is only used for unpacking files, the following shouldn't be an issue (storing owner/group of a file):
https://askubuntu.com/questions/1465853/difference-between-several-command-line-tools-provided-for-7-zip-compression-li

I've been using an Alpine image with 7zip since February 2023 on my ARM64 device with no issues. Unpacking encrypted files is about four times faster than with p7zip.

`apk add --no-cache 7zip` that's all

**Comment by phnzb** [comment]
@woiza I'll take a look next week, thank you

**Comment by woiza** [comment]
Are you going to use 7zip in v24?

**Comment by phnzb** [comment]
Definetly, yes. Coming soon to testing and will be included in v24 (and unrar 7.0 too).
