### ISSUE TITLE
`https://nzbget.com/documentation/building-development-version` needs an update

### ISSUE THREAD

**Issue by paul-chambers** [nzbgetcom/nzbget#87]
`https://nzbget.com/documentation/building-development-version/` needs to be updated, since there are no instructions about running `autoreconf` and friends. In other words, `git clone` followed by `./configure` will give an error since no `configure` script has been built yet.

p.s. I'm hoping that `cmake` is (or soon will become) the 'official' build method :)

**Comment by luckedea** [comment]
Good call, it's just difficult to maintain all the moving pieces during active development.
We'll try to keep technical information about development in the repo.
And use website for more generic information & documentation, for users.

Related PR https://github.com/nzbgetcom/nzbget/pull/137

**Comment by dnzbk** [comment]
Not relevant anymore. 
[Here](https://nzbget.com/documentation/installation-on-posix/) is an updated doc.
