### ISSUE TITLE
CMakeLists.txt doesn't check for boost as a dependency

### ISSUE THREAD

**Issue by paul-chambers** [nzbgetcom/nzbget#88]
`OpenSSL`, `ZLib` and `libxml2` are checked for in CMakeLists.txt, but not `boost`. CMake will complete without complaint, but the result will not build if `boost` is not installed.

By the way, it may be worth adding the equivalent package names for the popular distros to the build instructions, since less experienced developers may not know the mapping, or that it's not sufficient to have just the libraries installed, but also need the '-dev' packages to build against them.

_Environment_: Jetbrains CLion 2023.3.1, Ubuntu 23.10.

**Comment by dnzbk** [comment]
It acctually does in the tests subdir [CMakeLists.txt](https://github.com/nzbgetcom/nzbget/blob/develop/tests/CMakeLists.txt).
We are in the process of a soft migration from autotools to CMake and at the moment CMake is only used for tests and only on Windows.
In the near future we'll add support for other platforms (macOS, Linux, Embedded Linux) and completely drop autotools.
So we still have to use autotools on POSIX.

As for the '-dev' version, this is partially covered in [Installation on POSIX](https://nzbget.com/documentation/installation-on-posix/). It may also be worth adding such information to [INSTALATION.md](https://github.com/nzbgetcom/nzbget/blob/develop/INSTALLATION.md) for sure.
After the full migration to CMake we'll run through all the documentation and update it.
