### ISSUE TITLE
Linking `tests/feed/FeedTest` complains about the absence of `stricmp()`

### ISSUE THREAD

**Issue by paul-chambers** [nzbgetcom/nzbget#89]
Linking of `tests/feed/FeedTest` fails, complaining about the absence of `stricmp()`.

_Environment_: CMake, Jetbrains CLion 2023.3.1, Ubuntu 23.10

**Comment by dnzbk** [comment]
it's the same problem with CMake that was discussed [here](https://github.com/nzbgetcom/nzbget/issues/88#issuecomment-1880865238).
So we still have to use autotools on POSIX.
