### ISSUE TITLE
Provide .deb & .rpm packages (and repos to deliver them)

### ISSUE THREAD

**Issue by paul-chambers** [nzbgetcom/nzbget#92]
The title says it all... provide .deb and .rpm packages to install on the most popular desktop/server distributions. Preferably with repos that users can add, to receive updates through the same mechanism as they do the rest of their software.

There are valid arguments for & against having your own software installation and update mechanism. But no argument that says you cannot provide the choice.

It's in everyone's interests if the distro maintainers have to do as little as possible to the upstream projects' deliverables to make them available in their core distro repos. It helps keep the distros up-to-date - and aligned - with fixes and improvements being made here.

The .deb/.rpm packages themselves could simply contain installation scripts similar to the .run script already provided.

**Comment by dnzbk** [comment]
I like the idea.
I think we can easily do this using [CPackDeb](https://cmake.org/cmake/help/v3.6/module/CPackDeb.html) and [CPackRPM](https://cmake.org/cmake/help/v3.7/module/CPackRPM.html) CMake modules.

**Comment by luckedea** [comment]
We would pick this one up sooner with the intent to support as many "platforms" as we can to move forward.
NZBGet always was known to support multiple platforms efficiently.
Ongoing transition to CMake would also help with this project.
